/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa_transportes;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author monirami
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    MySQL db = new MySQL();
    CardLayout cardLayout;
    ArrayList<String> nombres_empleados = db.consultarEmpleados();
    
    public Ventana() {
        initComponents();
        cardLayout = (CardLayout) (cards_panel.getLayout());
        
        String[] nombres_array = nombres_empleados.toArray(new String[nombres_empleados.size()]);
        DefaultComboBoxModel<String> model_combobox_empleados = new DefaultComboBoxModel<>( nombres_array );
        guardar_horas_combobox.setModel(model_combobox_empleados);
        calcular_horas_combobox.setModel(model_combobox_empleados);
        cardLayout.show(cards_panel, "guardar_horas_card");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        capturar_horas_menu_button = new javax.swing.JButton();
        calcular_horas_extras_menu_button = new javax.swing.JButton();
        guardar_inventario_menu_button = new javax.swing.JButton();
        cards_panel = new javax.swing.JPanel();
        guardar_inventario_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombe_articulo_txtfield = new javax.swing.JTextField();
        cantidad_articulo_txtfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        guardar_articulo_button = new javax.swing.JButton();
        guardar_horas_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        guardar_horas_combobox = new javax.swing.JComboBox<>();
        guardar_horas_txtfield = new javax.swing.JTextField();
        guardar_horas_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calcular_horas_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        calcular_horas_combobox = new javax.swing.JComboBox<>();
        calcular_horas_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hrs_trabajadas_txtfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hrs_extras_txtfield = new javax.swing.JTextField();
        salario_txtfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        salario_extra_txtfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        capturar_horas_menu_button.setText("Guardas Horas");
        capturar_horas_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturar_horas_menu_buttonActionPerformed(evt);
            }
        });

        calcular_horas_extras_menu_button.setText("Calcular Horas Extras");
        calcular_horas_extras_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_horas_extras_menu_buttonActionPerformed(evt);
            }
        });

        guardar_inventario_menu_button.setText("Guardar Inventario");
        guardar_inventario_menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_inventario_menu_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(capturar_horas_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcular_horas_extras_menu_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardar_inventario_menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capturar_horas_menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            .addComponent(calcular_horas_extras_menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(guardar_inventario_menu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        cards_panel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Guardar Inventario");

        jLabel11.setText("Articulo");

        jLabel12.setText("Cantidad");

        guardar_articulo_button.setText("Guardar");
        guardar_articulo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_articulo_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guardar_inventario_panelLayout = new javax.swing.GroupLayout(guardar_inventario_panel);
        guardar_inventario_panel.setLayout(guardar_inventario_panelLayout);
        guardar_inventario_panelLayout.setHorizontalGroup(
            guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardar_inventario_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(guardar_inventario_panelLayout.createSequentialGroup()
                        .addGroup(guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombe_articulo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(28, 28, 28)
                        .addGroup(guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(guardar_inventario_panelLayout.createSequentialGroup()
                                .addComponent(cantidad_articulo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardar_articulo_button, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        guardar_inventario_panelLayout.setVerticalGroup(
            guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardar_inventario_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guardar_inventario_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombe_articulo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad_articulo_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar_articulo_button))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        cards_panel.add(guardar_inventario_panel, "guardar_inventario_card");

        jLabel2.setText("Guardar horas de la semana trabajadas del empleado");

        guardar_horas_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        guardar_horas_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_horas_comboboxActionPerformed(evt);
            }
        });

        guardar_horas_button.setText("Guardar");
        guardar_horas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_horas_buttonActionPerformed(evt);
            }
        });

        jLabel4.setText("Empleado");

        jLabel5.setText("Horas trabajadas");

        javax.swing.GroupLayout guardar_horas_panelLayout = new javax.swing.GroupLayout(guardar_horas_panel);
        guardar_horas_panel.setLayout(guardar_horas_panelLayout);
        guardar_horas_panelLayout.setHorizontalGroup(
            guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardar_horas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(guardar_horas_panelLayout.createSequentialGroup()
                        .addGroup(guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guardar_horas_combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 255, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(guardar_horas_panelLayout.createSequentialGroup()
                                .addComponent(guardar_horas_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(guardar_horas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap())
        );
        guardar_horas_panelLayout.setVerticalGroup(
            guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardar_horas_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guardar_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar_horas_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar_horas_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar_horas_button))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        cards_panel.add(guardar_horas_panel, "guardar_horas_card");

        jLabel3.setText("Calcular horas extras del empleado");

        calcular_horas_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        calcular_horas_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_horas_comboboxActionPerformed(evt);
            }
        });

        calcular_horas_button.setText("Calcular horas extras");
        calcular_horas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_horas_buttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Seleccione al empleado");

        hrs_trabajadas_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrs_trabajadas_txtfieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Horas Trabajadas");

        jLabel8.setText("Horas extras");

        hrs_extras_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrs_extras_txtfieldActionPerformed(evt);
            }
        });

        salario_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salario_txtfieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Salario");

        jLabel10.setText("Pago extra");

        salario_extra_txtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salario_extra_txtfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calcular_horas_panelLayout = new javax.swing.GroupLayout(calcular_horas_panel);
        calcular_horas_panel.setLayout(calcular_horas_panelLayout);
        calcular_horas_panelLayout.setHorizontalGroup(
            calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                        .addComponent(calcular_horas_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(calcular_horas_button, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                        .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hrs_trabajadas_txtfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hrs_extras_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel10))
                            .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                                .addComponent(salario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salario_extra_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        calcular_horas_panelLayout.setVerticalGroup(
            calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcular_horas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcular_horas_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular_horas_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(calcular_horas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrs_trabajadas_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrs_extras_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario_extra_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        cards_panel.add(calcular_horas_panel, "calcular_horas_card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cards_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cards_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capturar_horas_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturar_horas_menu_buttonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cards_panel, "guardar_horas_card");
    }//GEN-LAST:event_capturar_horas_menu_buttonActionPerformed

    private void guardar_inventario_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_inventario_menu_buttonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cards_panel, "guardar_inventario_card");
    }//GEN-LAST:event_guardar_inventario_menu_buttonActionPerformed

    private void calcular_horas_extras_menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_horas_extras_menu_buttonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(cards_panel, "calcular_horas_card");
    }//GEN-LAST:event_calcular_horas_extras_menu_buttonActionPerformed

    private void guardar_horas_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_horas_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardar_horas_comboboxActionPerformed

    private void guardar_horas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_horas_buttonActionPerformed
        // TODO add your handling code here:
        int horas = Integer.parseInt(guardar_horas_txtfield.getText());
        int empleado_id = Integer.parseInt(guardar_horas_combobox.getSelectedItem().toString().substring(0,1));
        System.out.println("hroras: "+horas);
        System.out.println("empleado_id: "+empleado_id);
        db.actualizarHorasTrabajadas(horas, empleado_id);
    }//GEN-LAST:event_guardar_horas_buttonActionPerformed

    private void calcular_horas_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_horas_comboboxActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_calcular_horas_comboboxActionPerformed

    private void calcular_horas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_horas_buttonActionPerformed
        // TODO add your handling code here:
        int empleado_id = Integer.parseInt(calcular_horas_combobox.getSelectedItem().toString().substring(0,1));
        Empleado empleado = db.consultarDatosEmpleado(empleado_id);
        System.out.println("empleado: "+empleado.nombre);
        hrs_trabajadas_txtfield.setText(Integer.toString(empleado.horas_trabajadas));
        hrs_extras_txtfield.setText(Integer.toString(empleado.horas_extras));
        salario_txtfield.setText(Integer.toString(empleado.salario));
        salario_extra_txtfield.setText(Integer.toString(empleado.salario_extra));
    }//GEN-LAST:event_calcular_horas_buttonActionPerformed

    private void hrs_extras_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrs_extras_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrs_extras_txtfieldActionPerformed

    private void salario_extra_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salario_extra_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salario_extra_txtfieldActionPerformed

    private void hrs_trabajadas_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrs_trabajadas_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrs_trabajadas_txtfieldActionPerformed

    private void salario_txtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salario_txtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salario_txtfieldActionPerformed

    private void guardar_articulo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_articulo_buttonActionPerformed
        // TODO add your handling code here:
        String nombre_articulo = nombe_articulo_txtfield.getText();
        int cantidad_articulo = Integer.parseInt(cantidad_articulo_txtfield.getText());
        db.guardarArticulo(nombre_articulo, cantidad_articulo);
        
    }//GEN-LAST:event_guardar_articulo_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular_horas_button;
    private javax.swing.JComboBox<String> calcular_horas_combobox;
    private javax.swing.JButton calcular_horas_extras_menu_button;
    private javax.swing.JPanel calcular_horas_panel;
    private javax.swing.JTextField cantidad_articulo_txtfield;
    private javax.swing.JButton capturar_horas_menu_button;
    private javax.swing.JPanel cards_panel;
    private javax.swing.JButton guardar_articulo_button;
    private javax.swing.JButton guardar_horas_button;
    private javax.swing.JComboBox<String> guardar_horas_combobox;
    private javax.swing.JPanel guardar_horas_panel;
    private javax.swing.JTextField guardar_horas_txtfield;
    private javax.swing.JButton guardar_inventario_menu_button;
    private javax.swing.JPanel guardar_inventario_panel;
    private javax.swing.JTextField hrs_extras_txtfield;
    private javax.swing.JTextField hrs_trabajadas_txtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nombe_articulo_txtfield;
    private javax.swing.JTextField salario_extra_txtfield;
    private javax.swing.JTextField salario_txtfield;
    // End of variables declaration//GEN-END:variables
}
